### ISSUE TITLE
deep merge with `failonmissingfiles=False` and missing file fails

### ISSUE THREAD

**Issue by t2d** [zerwes/hiyapyco#11]
#10 blocks deep merge with `failonmissingfiles=False`, because it still creates an empty dict for the missing file.

```
Traceback (most recent call last):
  File "./inventory/hiera.py", line 102, in <module>
    HieraInventory()
  File "./inventory/hiera.py", line 39, in __init__
    self.inventory = self.get_inventory(self.hiera_data)
  File "./inventory/hiera.py", line 83, in get_inventory
    method=hiyapyco.METHOD_MERGE)
  File "build/bdist.linux-x86_64/egg/hiyapyco/__init__.py", line 410, in load
  File "build/bdist.linux-x86_64/egg/hiyapyco/__init__.py", line 200, in __init__
  File "build/bdist.linux-x86_64/egg/hiyapyco/__init__.py", line 364, in _deepmerge
hiyapyco.HiYaPyCoImplementationException: can not merge <type 'NoneType'> to <class 'collections.OrderedDict'>....
```

**Comment by zerwes** [comment]
fixed @ 406cd1194bc4da911c2476ac9345d489bcda616d
test @ d3a68463ffd87b7e564df3f14c0eabd24ba52f63
